.gitignore
.vscode/launch.json
src/app.ts
src/git.ts
src/templates.ts
src/types.ts

This renames the expected repository YAML configuration naming from `<repository-name>.yaml` to `.config/templates.yaml` to make it clearer for teams what the file contents are expected to be. 
This also resolves a duplicate PR creation bug and avoid storing any files to disk when extracting templates.

Change expected configuration file naming

---

.github/workflows/release.yaml

This uses the newly added organisation secret for pushing images to https://hub.docker.com/u/pleo.

Use Docker Hub write token

---

.github/workflows/test.yaml
test/index.test.ts

This adds a workflow for running unit tests and generating a code coverage report on `push` events.
The tests are currently failing, so the workflow fails as expected.

Add test workflow running on pushes

---

src/app.ts
src/configuration.ts
src/git.ts
src/templates.ts

This updates all functions to _not_ take a `Probot` parameter. The only reason the logic currently looks this way is to allow calling `app.log.debug|info|warn`. 
Instead we use `console.debug|info|warn` to
- simplify the logic
- make it easier to test logic
Eventually we should use the logger underneath Probot ([`pino`](https://github.com/pinojs/pino)) to get really nice logging and ensure this logger is available for tests, but for now this will allow us to extend and test the logic without major loss of logging niceness.

Prefer console.log to Probot.log to avoid passing the app object around globally

---

src/app.ts
src/configuration.ts
src/git.ts
src/templates.ts
src/types.ts

This will refactor the app logic to take the required `Octokit` type instead of passing the full `Context` around. This refactor also moves the passing of the required `Octokit` type to the end of the function chains to allow preparing work and executing it at a later stage when an instance of Octokit is passed. 
This will make testing easier and make it more clear what the functions actually do based on the parameters they require.

Refactor functions to use Octokit directly instead of passing Context parameters

---

README.md
src/templates.ts
test/templates.test.ts

This will use the GitHub Actions-compatible delimiters `['<<<', '>>>']` for template rendering. The existing `{{` and `}}` delimiters are not compatible with GitHub Actions' `${{ ... }}` delimiters.

Use GitHub Action-compatible delimiters for template rendering

---

.eslintrc.js
package.json
src/app.ts
src/templates.ts
yarn.lock

This removes template release fetching for `latest`, since it's invalid and allows errors to bubble up for nicer error logging.

Hotfix release fetch and noisy error logging

---

.github/workflows/test.yaml
.swcrc
package.json
tsconfig.json
yarn.lock

This uses [`swc`](https://swc.rs/) for building the project and TypeScript's `tsc` only for type checking. 
This makes CI runs 200-300% faster and makes local development, debugging and testing close to instant with a 1600% build time speedup.

Use SWC for building

---

.github/workflows/test.yaml

`docker build` doesn't like `swc`, so we only use it for testing and CI to speed these up, but avoid using it for distributed images.

Prefer SWC only in tests and CI

---

app.yml

This adds administration permissions to the App manifest to allow automerging PRs.

Add administration permissions for automerge

---

src/app.ts
src/configuration.ts
src/git.ts
src/schema-validator.ts
src/types.ts
test/configuration.test.ts
test/git.test.ts
test/schema-validator.test.ts
yarn.lock

[Linear ticket](https://linear.app/pleo/issue/DX-721/add-errors-on-pr-comments)
This PR adds a comment on each error on the specific line where it failed. In order to do so, a CST ([Concrete Syntax Tree](https://en.wikipedia.org/wiki/Parse_tree)) is used as per https://eemeli.org/yaml/#parser, so all the content is preserved pristine. 
Once the validation is performed a list of errors with an instance path is received. For each error, the path is matched against the tree representation by performing a depth search. When the node is found, it is compared its offset against the line offset to find the particular line.
Example:

Send comment on PR errors per line

---

src/app.ts
src/git.ts
test/app.test.ts
test/git.test.ts

This will avoid creating PRs with 0 changed files. This is accomplished by comparing the base branch (the default branch) with the branch created for the configuration changes.

Avoid creating PRs with no changes

---

src/app.ts
src/git.ts
src/templates.ts
src/types.ts
test/app.test.ts

This changes the way createTree changes work. A bug has been reported that after changing a variable, the resulting PR didn't contain any change. After debugging the rendering was done fine but the resulting changes didn't contain any file changed. Now it applies the changes to a base commit, and simplifies the code resulting in less calls to GitHub API which were not needed
[Linear ticket](https://linear.app/pleo/issue/DX-726/values-updates-doesnt-trigger-template-generation)

Simplify code and fix createTreeChanges

---

package.json
src/app.ts
src/checks.ts
src/git.ts
src/schema-validator.ts
src/types.ts
test/checks.test.ts
test/git.test.ts

This PR moves the comment from being posted by the bot to being annotated as part of the check. The advantage is that is much more clear to see from which bot the changes come.
Example:

Move comments to checks

---

package.json
src/app.ts
src/start.ts
test/checks.test.ts

This PR changes the start script to use a custom `Server`, this is done so custom retry options can be passed to it. The reason to have custom retry options is because it has been observed that some times call to retrieve files from a pull request event received throws a 404 error, due likely an eventual consistency isue. By default octokit-retrier does not retry 404 errors. 
Related: https://github.com/probot/probot/discussions/1768#discussioncomment-4239894

Change start script to inject custom octokit retry options

---

src/app.ts
src/git.ts
test/git.test.ts

This will: 
- Prefer review comment creation to creating actual PR reviews
- Forward the success statuses of the validation to determine which comment to submit

Prefer commenting on PRs to submitting reviews

---

src/git.ts
test/git.test.ts

`createReviewComment` is not the expected endpoint for commenting on PRs - that'd (surprisingly) be `createReview` with `{... event: 'COMMENT'}` - good times.. 
This fixes #85 .

Fix invalid GitHub endpoint for PR review commenting

---

src/validation.ts

This fixes an `[Object object]` being logged after check creation/update in the logs and will instead use the `conclusion` property for useful logging.

Use check outcome for logging

---

src/git.ts

This ensures that labels are set according to the `env` property of the application configuration when PRs are created with file changes.

Ensure label creation on PR creation

---

src/schema-validator.ts

This extends the error message for missing files in releases. This should reduce confusion when a file has been removed in a later version.

Extend validation errors for missing files in releases
